CREATE TABLE IF NOT EXISTS subscriptions(endpoint TEXT PRIMARY KEY,owner TEXT NOT NULL,payload TEXT NOT NULL,updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS deliveries(id TEXT PRIMARY KEY,at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS deliveries_age ON deliveries(at);
