import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {camera,drawRoomEdges,visibleHotspot,ART_W,ART_H} from './art';
import {MAP_ART} from './mapArt';
import {loadAssets,drawPart,character,ITEM_ART,itemId} from './itemArt';
import {HOTSPOTS} from './art';
import {mapInfo,type MapId} from './maps';
import {clock,ownedOnMap,type PixelState} from './model';
import {prepareHands,drawHands,handPose} from './motion';
import {composeRoom} from './composition';
function glow(c:CanvasRenderingContext2D,x:number,y:number,r:number,alpha:number,color='255,172,62'){c.save();c.globalCompositeOperation='screen';const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,`rgba(${color},${alpha})`);g.addColorStop(1,`rgba(${color},0)`);c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2);c.restore();}

export default function NewScene(props:{state:PixelState;mapId:MapId;running:boolean;bpm:number;flash:number;onClock:()=>void;onMetro:()=>void;onBack:()=>void;onShop?:()=>void;onObject:(id:string)=>void;interactive?:boolean}){
 const frame=useRef<HTMLDivElement>(null),cv=useRef<HTMLCanvasElement>(null),live=useRef(props);live.current=props;const [size,setSize]=useState({width:1,height:1}),[load,setLoad]=useState('Carico la stanza…');const geom=useRef(size);geom.current=size;const id=props.mapId;
 useEffect(()=>{const o=new ResizeObserver(([e])=>setSize({width:e.contentRect.width,height:e.contentRect.height}));if(frame.current)o.observe(frame.current);return()=>o.disconnect();},[]);
 useEffect(()=>{let alive=true,raf=0,last=0,cacheKey:null|string=null;setLoad('Carico la stanza…');const images=[new Image(),new Image()];Promise.all(images.map((im,i)=>new Promise<void>((ok,no)=>{im.onload=()=>ok();im.onerror=no;im.src=id==='home'?`/pixel/${i?'empty-v2':'neutral-v2'}.webp`:`/pixel/${id}-${i?'base':'full'}.webp`;}))).then(async()=>{const assets=await loadAssets(id);if(id==='home')assets.toolsBase=images[0];if(!alive)return;setLoad('');const [full,base]=images;const actor=document.createElement('canvas');actor.width=ART_W;actor.height=ART_H;drawPart(actor.getContext('2d')!,assets,character);const motion=prepareHands(actor),art=id==='home'?{clock:[705,256,133,40],lights:[[876,286],[233,789]]}:MAP_ART[id];const room=document.createElement('canvas');room.width=ART_W;room.height=ART_H;const rc=room.getContext('2d')!;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const draw=(now:number)=>{if(!alive)return;raf=requestAnimationFrame(draw);if(now-last<45||document.hidden)return;last=now;const {state:p,running,bpm,flash}=live.current;const owned=ownedOnMap(p,id),key=owned.join('|');
 if(key!==cacheKey){cacheKey=key;composeRoom(rc,base,id,owned,assets,false);}
 const el=cv.current;if(!el)return;const {width:w,height:h}=geom.current;if(w<2||h<2)return;const dpr=Math.min(2,devicePixelRatio||1);if(el.width!==Math.round(w*dpr)||el.height!==Math.round(h*dpr)){el.width=Math.round(w*dpr);el.height=Math.round(h*dpr);}const c=el.getContext('2d');if(!c)return;const cam=camera(w,h),t=now/1000,active=p.session?.status==='running';c.setTransform(dpr,0,0,dpr,0,0);c.imageSmoothingEnabled=false;
 drawRoomEdges(c,base,w,h,cam,{home:970,studio:920,shop:500,rehearsal:620,stage:500}[id]);
 // The complete map fits; edge continuation uses only this map's empty background.
 c.translate(cam.x,cam.y);c.scale(cam.scale,cam.scale);c.drawImage(room,0,0);c.save();const pose=handPose(t,active,reduced);c.translate(pose.lean,active&&!reduced?Math.sin(t*1.4)*.6:0);c.drawImage(motion.clean,0,0);drawHands(c,motion,t,active,reduced);c.restore();
 if(owned.includes(itemId(id,id==='home'?'plant':'plants'))&&!reduced){c.save();c.globalAlpha=.06*(1+Math.sin(t*.8));for(const p of ITEM_ART[id][id==='home'?'plant':'plants']??[])drawPart(c,assets,p,Math.sin(t*.6));c.restore();}
 if(id==='home'){if(p.rainOn){c.save();c.beginPath();[[269,250,83,111],[368,250,99,111],[269,381,83,146],[368,381,99,146]].forEach(q=>c.rect(...q as [number,number,number,number]));c.clip();for(let i=0;i<44;i++){const x=270+(i*47)%197,y=241+((t*130+i*31)%305);c.globalAlpha=.35+(i%3)*.13;c.fillStyle=i%3?'#7388b0':'#b6b7cf';c.fillRect(x,y,2,10+(i%4)*3);}c.restore();}
 if(owned.includes('fire')&&p.fireOn){c.save();c.beginPath();c.rect(24,634,99,150);c.clip();for(let i=0;i<5;i++){const x=36+i*19,hf=40+(Math.sin((reduced?0:t)*5+i*1.8)+1)*28;for(let y=0;y<hf;y+=7){const ww=Math.max(7,28-Math.floor(y/hf*4)*7);c.fillStyle=y<hf*.45?'#ff9229':y<hf*.8?'#ffbe37':'#ffe176';c.fillRect(x-ww/2+Math.round(Math.sin(t*4+i+y*.04))*5,778-y,ww,7);}}c.restore();glow(c,79,719,240,.11+.025*Math.sin(t*6));}
 if(owned.includes('cat')&&!reduced&&t%7.4<.16){c.fillStyle='#2b2534';c.fillRect(126,455,8,5);c.fillRect(144,455,8,5);}if(owned.includes('desk')&&p.deskLightOn)glow(c,233,789,260,.18);if(owned.includes('lamp')){c.fillStyle='#684129';c.fillRect(861,269,31,36);c.fillStyle=p.lampOn?'#ffe5a0':'#3e2c2c';c.fillRect(867,274,18,24);if(p.lampOn)glow(c,876,286,130,.18);}}
 c.save();c.translate(708,971);c.rotate(running?Math.sin(t*Math.PI*bpm/60)*.45:0);c.fillStyle='#ecba55';c.fillRect(-2,-79,4,79);c.fillRect(-7,-72,14,10);c.restore();if(running&&flash){c.fillStyle='#ffd783';c.fillRect(697,981,22,2);}
 // Soft ambient activity continues independently of the metronome.
 const pulse=reduced?.06:.07+.018*Math.sin(t*.9);if(id!=='home'&&p.lampOn)for(const [x,y]of art.lights)glow(c,x,y,130,pulse,id==='stage'&&x>250&&x<700?'156,114,222':'255,172,62');
 if(id==='studio'&&owned.includes('studio:monitors'))for(let i=0;i<10;i++){const height=10+(reduced?12:(Math.sin(t*2+i)+1)*17);c.fillStyle=i%4?'#94bc43':'#e4a74a';c.fillRect(185+i*18,605-height,4,height);}
 if(id==='studio'&&owned.includes('studio:rack'))for(let i=0;i<8;i++){c.fillStyle=Math.sin(t*1.3+i)>.5?'#c5df62':'#41602f';c.fillRect(818+(i%4)*23,557+Math.floor(i/4)*86,5,5);}
 if(id==='shop'&&p.lampOn&&owned.includes('shop:cabinet')){glow(c,846,644,250,pulse*.75);if(!reduced){c.fillStyle='#ffd87b';for(let i=0;i<6;i++)c.fillRect(758+(i*53)%179,360+(t*13+i*91)%568,2,2);}}
 if(id==='rehearsal'&&owned.includes('rehearsal:amps')){c.fillStyle='#ffd076';c.fillRect(782,608,6,5);c.globalAlpha=reduced?.5:.5+.4*Math.sin(t);c.fillRect(860,753,6,5);c.globalAlpha=1;}
 if(id==='rehearsal'&&owned.includes('rehearsal:pedals'))for(let i=0;i<3;i++){c.fillStyle=i%2?'#65bf9f':'#eacc72';c.fillRect(859+i*57,1248,3,3);}
 if(!reduced){c.save();c.globalAlpha=.35;c.fillStyle=id==='stage'?'#c4abdf':'#dab589';for(let i=0;i<18;i++)c.fillRect(80+(i*139)%850,150+(t*7+i*67)%1050,2,2);c.restore();}
 if(id==='stage'&&p.lampOn&&!reduced){c.save();c.globalAlpha=.045+.02*Math.sin(t*.7);c.fillStyle='#b5a0e3';c.beginPath();c.moveTo(378,230);c.lineTo(310+Math.sin(t*.4)*25,900);c.lineTo(590+Math.sin(t*.4)*25,900);c.fill();c.restore();}
 if(id!=='home'&&!p.lampOn){c.save();c.globalCompositeOperation='multiply';for(const [lx,ly]of art.lights){const shade=c.createRadialGradient(lx,ly,8,lx,ly,155);shade.addColorStop(0,'rgba(28,22,34,.86)');shade.addColorStop(.45,'rgba(40,28,38,.55)');shade.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=shade;c.fillRect(lx-155,ly-155,310,310);}c.restore();}c.setTransform(dpr,0,0,dpr,0,0);const clockBox=visibleHotspot(cam,w,h,art.clock),[x,y,ww,hh]=art.clock;if(id==='home'||Math.abs(clockBox.x-(cam.x+x*cam.scale))>1||Math.abs(clockBox.y-(cam.y+y*cam.scale))>1)c.drawImage(id==='home'?full:base,x-8,y-9,ww+16,hh+18,clockBox.x-8*cam.scale,clockBox.y-9*cam.scale,clockBox.w+16*cam.scale,clockBox.h+18*cam.scale);c.fillStyle='#17151e';c.fillRect(clockBox.x,clockBox.y,clockBox.w,clockBox.h);c.fillStyle='#ffb740';c.font=`bold ${25*cam.scale}px monospace`;c.textAlign='center';c.textBaseline='middle';c.fillText(clock(p.session?.activeMs??0),clockBox.x+clockBox.w/2,clockBox.y+clockBox.h/2);
 };raf=requestAnimationFrame(draw);}).catch(()=>alive&&setLoad('La mappa non si è caricata. Ricarica la pagina.'));return()=>{alive=false;cancelAnimationFrame(raf);};},[id]);
 const art=id==='home'?{clock:[705,256,133,40],lights:[[876,286],[233,789]]}:MAP_ART[id],cam=camera(size.width,size.height);const hot=(label:string,q:readonly number[],onClick:()=>void,pressed?:boolean)=><button className="px-hot" key={label} aria-label={label} aria-pressed={pressed} onClick={onClick} style={(()=>{const box=label==='Orologio della sessione'?visibleHotspot(cam,size.width,size.height,q):{x:cam.x+q[0]*cam.scale,y:cam.y+q[1]*cam.scale,w:q[2]*cam.scale,h:q[3]*cam.scale};return {left:box.x,top:box.y,width:box.w,height:box.h} as CSSProperties;})()}/>;
 return <div ref={frame} className="px-scene" role="group" aria-label={`${mapInfo(id).name}, ambiente di studio interattivo`}><canvas ref={cv} aria-label={`${mapInfo(id).name}, chitarrista e arredi acquistati`}/>{load&&<div className="px-load">{load}</div>}{props.interactive!==false&&<><button className="px-back" aria-label="Torna alla schermata precedente" onClick={props.onBack}><svg viewBox="0 0 52 44" aria-hidden="true"><path fill="#ffca92" d="M0 20h4v-4h4v-4h4V8h4V4h4v12h28v12H20v12h-4v-4h-4v-4H8v-4H4v-4H0Z"/></svg></button>{hot('Orologio della sessione',art.clock,props.onClock)}{hot('Apri il metronomo originale',[657,871,108,124],props.onMetro)}{id==='home'&&<>{hot('Attiva o disattiva la pioggia',HOTSPOTS.rain,()=>props.onObject('rain'),props.state.rainOn)}{props.state.owned.includes('fire')&&hot('Accendi o spegni il camino',HOTSPOTS.fire,()=>props.onObject('fire'),props.state.fireOn)}{props.state.owned.includes('desk')&&hot('Accendi o spegni la luce della scrivania',HOTSPOTS.deskLight,()=>props.onObject('deskLight'),props.state.deskLightOn)}</>}{hot('Accendi o spegni le luci',art.lights[0].concat([80,80]).map((v,i)=>i<2?v-40:v),()=>props.onObject('lamp'),props.state.lampOn)}{props.onShop&&<button className="px-preview-shop" onClick={props.onShop}>Arreda la stanza</button>}</>}</div>;
}
