import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {camera,ART_W,ART_H} from './art';
import {MAP_ART,NEW_CORE,NEW_UPPER,type Poly} from './mapArt';
import {mapInfo,type MapId} from './maps';
import {clock,itemsForMap,ownedOnMap,type PixelState} from './model';
import {prepareHands,drawHands,handPose} from './motion';
function path(c:CanvasRenderingContext2D,p:Poly){c.moveTo(...p[0] as [number,number]);p.slice(1).forEach(q=>c.lineTo(...q as [number,number]));c.closePath();}
function mask(c:CanvasRenderingContext2D,im:CanvasImageSource,p:Poly,exclude=false,dx=0,dy=0){c.save();c.translate(dx,dy);c.beginPath();path(c,p);c.clip();if(exclude){c.beginPath();c.rect(0,0,ART_W,ART_H);path(c,NEW_CORE);c.clip('evenodd');}c.drawImage(im,0,0,ART_W,ART_H);c.restore();}

function rect(c:CanvasRenderingContext2D,im:CanvasImageSource,q:number[]){c.drawImage(im,q[0],q[1],q[2],q[3],q[0],q[1],q[2],q[3]);}
function glow(c:CanvasRenderingContext2D,x:number,y:number,r:number,alpha:number,color='255,172,62'){c.save();c.globalCompositeOperation='screen';const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,`rgba(${color},${alpha})`);g.addColorStop(1,`rgba(${color},0)`);c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2);c.restore();}
export default function NewScene(props:{state:PixelState;mapId:Exclude<MapId,'home'>;running:boolean;bpm:number;flash:number;onClock:()=>void;onMetro:()=>void;onBack:()=>void;onShop?:()=>void;onObject:(id:string)=>void;interactive?:boolean}){
 const frame=useRef<HTMLDivElement>(null),cv=useRef<HTMLCanvasElement>(null),live=useRef(props);live.current=props;const [size,setSize]=useState({width:1,height:1}),[load,setLoad]=useState('Carico la stanza…');const geom=useRef(size);geom.current=size;const id=props.mapId;
 useEffect(()=>{const o=new ResizeObserver(([e])=>setSize({width:e.contentRect.width,height:e.contentRect.height}));if(frame.current)o.observe(frame.current);return()=>o.disconnect();},[]);
 useEffect(()=>{let alive=true,raf=0,last=0,cacheKey='';setLoad('Carico la stanza…');const images=[new Image(),new Image()];Promise.all(images.map((im,i)=>new Promise<void>((ok,no)=>{im.onload=()=>ok();im.onerror=no;im.src=`/pixel/${id}-${i?'base':'full'}.webp`;}))).then(()=>{if(!alive)return;setLoad('');const [full,base]=images;const motion=prepareHands(full),art=MAP_ART[id],info=mapInfo(id);const room=document.createElement('canvas');room.width=ART_W;room.height=ART_H;const rc=room.getContext('2d')!;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const draw=(now:number)=>{if(!alive)return;raf=requestAnimationFrame(draw);if(now-last<45||document.hidden)return;last=now;const {state:p,running,bpm,flash}=live.current;const owned=ownedOnMap(p,id),key=owned.join('|');
 if(key!==cacheKey){cacheKey=key;rc.clearRect(0,0,ART_W,ART_H);rc.drawImage(base,0,0,ART_W,ART_H);const all=itemsForMap(id).every(i=>owned.includes(i.id));if(all){rc.drawImage(full,0,0,ART_W,ART_H);mask(rc,base,NEW_CORE);}else for(const [item,shapes]of Object.entries(art.layers))if(owned.includes(`${id}:${item}`))for(const shape of shapes)mask(rc,full,shape,true);rect(rc,base,[22,44,72,66]);rect(rc,base,[669,883,90,111]);rect(rc,base,art.clock);}
 const el=cv.current;if(!el)return;const {width:w,height:h}=geom.current;if(w<2||h<2)return;const dpr=Math.min(2,devicePixelRatio||1);if(el.width!==Math.round(w*dpr)||el.height!==Math.round(h*dpr)){el.width=Math.round(w*dpr);el.height=Math.round(h*dpr);}const c=el.getContext('2d');if(!c)return;const cam=camera(w,h),t=now/1000,active=p.session?.status==='running',pose=handPose(t,active,reduced);c.setTransform(dpr,0,0,dpr,0,0);c.imageSmoothingEnabled=false;
 // Extend architectural pixels with the SAME scale; no black letterboxing or stretched sprites.
 c.fillStyle=info.color;c.fillRect(0,0,w,h);const topEnd=Math.max(0,cam.y);if(topEnd)c.drawImage(base,100,0,700,80,0,0,w,topEnd);const bottom=cam.y+ART_H*cam.scale;if(bottom<h){c.save();c.translate(cam.x,bottom);c.scale(cam.scale,cam.scale);c.fillStyle=id==='stage'?'#351c30':'#925335';c.fillRect(-cam.x/cam.scale,0,w/cam.scale,(h-bottom)/cam.scale);for(let yy=0;yy<(h-bottom)/cam.scale;yy+=70){c.fillStyle=id==='stage'?'#4b2434':'#68402f';c.fillRect(-cam.x/cam.scale,yy,w/cam.scale,4);for(let xx=-1004;xx<w/cam.scale;xx+=270)c.fillRect(xx+((yy/70)%2)*135,yy,3,70);}c.restore();}
 const floor=cam.y+info.floor*cam.scale;c.save();c.translate(0,0);for(let y=0;y<h;y+=70*cam.scale){c.fillStyle=y<floor?info.color:id==='stage'?'#321c30':'#855038';if(cam.x>0){c.fillRect(0,y,cam.x,67*cam.scale);c.fillRect(cam.x+ART_W*cam.scale,y,cam.x,67*cam.scale);}}c.restore();c.translate(cam.x,cam.y);c.scale(cam.scale,cam.scale);c.drawImage(room,0,0);
 mask(c,motion.clean,NEW_CORE);if(active&&!reduced){mask(c,room,NEW_UPPER);mask(c,motion.clean,NEW_UPPER, false,pose.lean,Math.sin(t*1.4)*.6);}drawHands(c,motion,t,active,reduced);
 c.save();c.translate(708,971);c.rotate(running?Math.sin(t*Math.PI*bpm/60)*.45:0);c.fillStyle='#ecba55';c.fillRect(-2,-79,4,79);c.fillRect(-7,-72,14,10);c.restore();if(running&&flash){c.fillStyle='#ffd783';c.fillRect(697,981,22,2);}
 // Soft ambient activity continues independently of the metronome.
 const pulse=reduced?.06:.07+.018*Math.sin(t*.9);if(p.lampOn)for(const [x,y]of art.lights)glow(c,x,y,130,pulse,id==='stage'&&x>250&&x<700?'156,114,222':'255,172,62');
 if(id==='studio'&&owned.includes('studio:monitors'))for(let i=0;i<10;i++){const height=10+(reduced?12:(Math.sin(t*2+i)+1)*17);c.fillStyle=i%4?'#94bc43':'#e4a74a';c.fillRect(34+i*42,640-height,5,height);}
 if(id==='studio'&&owned.includes('studio:rack'))for(let i=0;i<8;i++){c.fillStyle=Math.sin(t*1.3+i)>.5?'#c5df62':'#41602f';c.fillRect(818+(i%4)*23,557+Math.floor(i/4)*86,5,5);}
 if(id==='shop'&&owned.includes('shop:cabinet')){glow(c,846,644,250,pulse*.75);if(!reduced){c.fillStyle='#ffd87b';for(let i=0;i<6;i++)c.fillRect(758+(i*53)%179,360+(t*13+i*91)%568,2,2);}}
 if(id==='rehearsal'&&owned.includes('rehearsal:amps')){c.fillStyle='#ffd076';c.fillRect(782,608,6,5);c.globalAlpha=reduced?.5:.5+.4*Math.sin(t);c.fillRect(860,753,6,5);c.globalAlpha=1;}
 if(id==='rehearsal'&&owned.includes('rehearsal:pedals'))for(let i=0;i<3;i++){c.fillStyle=i%2?'#65bf9f':'#eacc72';c.fillRect(859+i*57,1248,3,3);}
 if(!reduced){c.save();c.globalAlpha=.35;c.fillStyle=id==='stage'?'#c4abdf':'#dab589';for(let i=0;i<18;i++)c.fillRect(80+(i*139)%850,150+(t*7+i*67)%1050,2,2);c.restore();}
 if(id==='stage'&&!reduced){c.save();c.globalAlpha=.045+.02*Math.sin(t*.7);c.fillStyle='#b5a0e3';c.beginPath();c.moveTo(378,230);c.lineTo(310+Math.sin(t*.4)*25,900);c.lineTo(590+Math.sin(t*.4)*25,900);c.fill();c.restore();}
 const [x,y,ww,hh]=art.clock;c.fillStyle='#17151e';c.fillRect(x,y,ww,hh);c.fillStyle='#ffb740';c.font='bold 25px monospace';c.textAlign='center';c.textBaseline='middle';c.fillText(clock(p.session?.activeMs??0),x+ww/2,y+hh/2);
 };raf=requestAnimationFrame(draw);}).catch(()=>alive&&setLoad('La mappa non si è caricata. Ricarica la pagina.'));return()=>{alive=false;cancelAnimationFrame(raf);};},[id]);
 const art=MAP_ART[id],cam=camera(size.width,size.height);const hot=(label:string,q:number[],onClick:()=>void,pressed?:boolean)=><button className="px-hot" key={label} aria-label={label} aria-pressed={pressed} onClick={onClick} style={{left:cam.x+q[0]*cam.scale,top:cam.y+q[1]*cam.scale,width:q[2]*cam.scale,height:q[3]*cam.scale} as CSSProperties}/>;
 return <div ref={frame} className="px-scene" role="group" aria-label={`${mapInfo(id).name}, ambiente di studio interattivo`}><canvas ref={cv} aria-label={`${mapInfo(id).name}, chitarrista e arredi acquistati`}/>{load&&<div className="px-load">{load}</div>}{props.interactive!==false&&<><button className="px-back" aria-label="Torna alla schermata precedente" onClick={props.onBack}><svg viewBox="0 0 52 44" aria-hidden="true"><path fill="#ffca92" d="M0 20h4v-4h4v-4h4V8h4V4h4v12h28v12H20v12h-4v-4h-4v-4H8v-4H4v-4H0Z"/></svg></button>{hot('Orologio della sessione',art.clock,props.onClock)}{hot('Apri il metronomo originale',[657,871,108,124],props.onMetro)}{hot('Accendi o spegni le luci',art.lights[0].concat([80,80]).map((v,i)=>i<2?v-40:v),()=>props.onObject('lamp'),props.state.lampOn)}{props.onShop&&<button className="px-preview-shop" onClick={props.onShop}>Arreda la stanza</button>}</>}</div>;
}
