import { useCallback,useEffect,useRef,useState,type ReactNode } from 'react';
import { store,useStore } from '../data/store';
import MetronomeScreen from '../screens/MetronomeScreen';
import Scene,{Sprite} from './Scene';
import { ITEMS,begin,pause,resume,finish,tick,buy,bonusFor,completed,clock,money,type Receipt } from './model';
import { pixel,usePixel } from './state';
import './pixel.css';
function Popup({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}) {
 const box=useRef<HTMLElement>(null);
 useEffect(()=>{const old=document.activeElement as HTMLElement;box.current?.focus();const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'){const all=box.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);old?.focus();};},[onClose]);
 return <div className="px-veil" onClick={onClose}><section className="px-dialog" ref={box} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button onClick={onClose} aria-label="Chiudi finestra">×</button></header>{children}</section></div>;
}
export default function PixelStory({active}:{active:boolean}) {
 const st=useStore();const p=usePixel();const [scene,setScene]=useState(false);const [shop,setShop]=useState(false);const [exit,setExit]=useState(false);const [timer,setTimer]=useState(false);const [metro,setMetro]=useState(false);const [receipt,setReceipt]=useState<Receipt|null>(null);const [selected,setSelected]=useState('');const [stopSignal,setStopSignal]=useState(0);const [met,setMet]=useState({running:false,bpm:100,flash:0});const [delta,setDelta]=useState<{id:number;amount:number}|null>(null);const [notice,setNotice]=useState('');const lastEuro=useRef(Math.floor(p.balanceCents/100));
 const closeShop=useCallback(()=>setShop(false),[]), closeExit=useCallback(()=>setExit(false),[]), closeTimer=useCallback(()=>setTimer(false),[]), closeReceipt=useCallback(()=>setReceipt(null),[]);
 const metState=useCallback((running:boolean,bpm:number,flash:number)=>setMet({running,bpm,flash}),[]);
 const floating=(amount:number)=>setDelta({id:Date.now(),amount});
 const flushReceipts=useCallback(async()=>{for(const r of pixel.get().receipts.filter(r=>!r.recorded)){await store.recordPixelSession(r.id,r.songId,r.startedAt,r.activeMs/1000);pixel.update(s=>({...s,receipts:s.receipts.map(x=>x.id===r.id?{...x,recorded:true}:x)}));}},[]);
 useEffect(()=>{flushReceipts();},[flushReceipts]);
 useEffect(()=>{const t=window.setInterval(()=>{if(active&&pixel.get().session?.status==='running')pixel.update(s=>tick(s,Date.now()));},500);const stop=()=>pixel.update(s=>pause(s,Date.now()));window.addEventListener('pagehide',stop);return()=>{clearInterval(t);window.removeEventListener('pagehide',stop);stop();};},[active]);
 useEffect(()=>{if(!active){pixel.update(s=>pause(s,Date.now()));setScene(false);setMetro(false);setStopSignal(v=>v+1);}},[active]);
 useEffect(()=>{const euro=Math.floor(p.balanceCents/100);if(euro>lastEuro.current&&p.session?.status==='running')floating((euro-lastEuro.current)*100);lastEuro.current=euro;},[p.balanceCents,p.session?.status]);
 useEffect(()=>{if(!delta)return;const t=setTimeout(()=>setDelta(null),1800);return()=>clearTimeout(t);},[delta]);
 useEffect(()=>{if(!scene||!active)return;document.body.classList.add('pixel-session');let lock:{release:()=>void}|undefined;const request=async()=>{try{lock=await (navigator as Navigator & {wakeLock?:{request:(s:string)=>Promise<{release:()=>void}>}}).wakeLock?.request('screen');}catch{}};void request();return()=>{document.body.classList.remove('pixel-session');lock?.release();};},[scene,active]);
 const pauseAndLeave=()=>{pixel.update(s=>pause(s,Date.now()));setScene(false);setExit(false);setMetro(false);setStopSignal(v=>v+1);};
 const end=()=>{if(!pixel.update(s=>finish(s,Date.now())))return;void flushReceipts();setReceipt(pixel.get().receipts[0]??null);setScene(false);setExit(false);setTimer(false);setMetro(false);setStopSignal(v=>v+1);};
 const start=()=>{let song=st.songs.find(s=>s.id===selected);if(!song){song=store.addSong('Studio libero');}const s=song;const ok=pixel.update(v=>begin(v,s.id,s.title,Date.now(),`px-${crypto.randomUUID()}`));if(ok)setScene(true);};
 const doResume=()=>{if(pixel.update(s=>resume(s,Date.now())))setScene(true);};
 const bonus=bonusFor(p.owned);const required=ITEMS.filter(i=>i.required);const progress=required.filter(i=>p.owned.includes(i.id)).length;
 const buyItem=(id:string)=>{const i=ITEMS.find(i=>i.id===id)!;if(pixel.update(s=>buy(s,id))){floating(-i.price*100);setNotice(`${i.name} è nella tua stanza!`);}};
 const interact=(id:string)=>pixel.update(s=>({...s,...(id==='rain'?{rainOn:!s.rainOn}:id==='lamp'?{lampOn:!s.lampOn}:{fireOn:!s.fireOn})}));
 return <div className={`px-root ${scene?'px-in-session':''}`}>
  <button className="px-cheat" onClick={()=>{if(pixel.update(s=>({...s,balanceCents:s.balanceCents+100000})))floating(100000);}}>+ 1000 soldi</button>
  {pixel.getError()&&<div className="px-error" role="alert">{pixel.getError()}</div>}
  {!scene&&<div className="px-lobby"><div className="px-eyebrow">IL TUO ANGOLO DI MUSICA</div><h1>Pixel Story</h1><p>Un minuto di studio. Un pezzetto di casa.</p><div className="px-wallet"><span>Saldo virtuale</span><strong data-testid="pixel-balance">{money(p.balanceCents)}</strong><span>Bonus permanente +{bonus}%</span></div><div className="px-preview"><Scene state={p} running={false} bpm={met.bpm} flash={0} onClock={()=>setTimer(true)} onMetro={()=>setMetro(true)} onBack={()=>setNotice('Avvia una sessione per entrare nella stanza.')} onShop={()=>setShop(true)} onObject={interact}/></div><div className="px-map-title"><h2>Casa di legno</h2><span>{progress}/{required.length} essenziali</span></div><div className="px-progress"><i style={{width:`${progress/required.length*100}%`}}/></div>{completed(p)&&<p className="px-complete">✦ Casa completata! Le altre ambientazioni arriveranno nel prossimo aggiornamento.</p>}
   {p.session?<div className="px-session-card"><strong>Sessione in pausa · {p.session.title}</strong><span>{clock(p.session.activeMs)} · {money(p.session.earnedCents)} guadagnati</span><button className="px-primary" onClick={doResume}>Riprendi lo studio</button><button onClick={end}>Termina e salva</button></div>:<><label className="px-select-label">Cosa studi?<select aria-label="Brano della sessione" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Studio libero</option>{st.songs.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><button className="px-primary px-start" onClick={start}>Entra e inizia a studiare</button></>}
   <div className="px-lobby-actions"><button onClick={()=>{setNotice('');setShop(true);}}>Negozio e arredi</button><button onClick={()=>{store.updateSettings({pixelStory:false});}}>Torna allo Studio classico</button></div><p className="px-small">1€ virtuale / minuto effettivo · Le pause non producono soldi.<br/>Il bonus viene fissato all’inizio di ogni sessione.</p>
  </div>}
  {scene&&<div className="px-stage"><Scene state={p} running={met.running} bpm={met.bpm} flash={met.flash} onClock={()=>setTimer(true)} onMetro={()=>setMetro(true)} onBack={()=>setExit(true)} onObject={interact}/>{p.session?.status==='paused'&&<button className="px-resume-overlay" onClick={()=>pixel.update(s=>resume(s,Date.now()))}>In pausa · Riprendi</button>}</div>}
  {delta&&<div key={delta.id} className={`px-money-float ${delta.amount<0?'px-negative':''}`} aria-live="polite">{delta.amount>=0?'+':''}{money(delta.amount)}</div>}
  {shop&&<Popup title="Negozio della Casa di legno" onClose={closeShop}><div className="px-shop-top"><strong>{money(p.balanceCents)}</strong><span>Bonus +{bonus}%</span></div>{notice&&<p role="status" className="px-notice">{notice}</p>}<p className="px-small">Completa i 6 arredi essenziali. Gli extra sono facoltativi.</p><div className="px-shop-grid">{ITEMS.map(i=><article key={i.id} className={p.owned.includes(i.id)?'px-owned':''}><div className="px-item-art">{i.tile!==undefined?<Sprite tile={i.tile}/>:<span className="px-fire-icon">♨</span>}</div><div className="px-item-copy"><span className="px-item-type">{i.required?'ESSENZIALE':'EXTRA'}{i.bonus>0?` · +${i.bonus}%`:''}</span><h3>{i.name}</h3><p>{i.description}</p><button aria-label={p.owned.includes(i.id)?`${i.name} acquistato`:`Compra ${i.name}`} disabled={p.owned.includes(i.id)||p.balanceCents<i.price*100} onClick={()=>buyItem(i.id)}>{p.owned.includes(i.id)?'✓ Nella stanza':`${i.price}€ · Compra`}</button></div></article>)}</div></Popup>}
  {exit&&<Popup title="Lasci la tua stanza?" onClose={closeExit}><p>Hai studiato {clock(p.session?.activeMs??0)}. Il metronomo continua finché scegli cosa fare.</p><div className="px-dialog-actions"><button className="px-primary" onClick={pauseAndLeave}>Metti in pausa</button><button onClick={end}>Termina sessione</button><button onClick={closeExit}>Annulla</button></div></Popup>}
  {timer&&<Popup title="Orologio di studio" onClose={closeTimer}><div className="px-timer-big" data-testid="pixel-elapsed">{clock(p.session?.activeMs??0)}</div><p>{p.session?.title??'Nessuna sessione avviata'} · {p.session?.status==='running'?'In corso':'In pausa'}</p><p>Guadagnati: <strong>{money(p.session?.earnedCents??0)}</strong><br/>1€/min + {p.session?.bonus??bonus}%</p>{p.session&&<button className="px-primary" onClick={()=>{if(pixel.get().session?.status==='running')setStopSignal(v=>v+1);pixel.update(s=>s.session?.status==='running'?pause(s,Date.now()):resume(s,Date.now()));}}>{p.session.status==='running'?'Metti in pausa il tempo':'Riprendi il tempo'}</button>}</Popup>}
  {receipt&&<Popup title="Una bella sessione ✦" onClose={closeReceipt}><p>{receipt.title}</p><div className="px-timer-big">{clock(receipt.activeMs)}</div><div className="px-reward">+{money(receipt.earnedCents)}</div><p>Base {money(Math.floor(receipt.activeMs/600))} · bonus +{receipt.bonus}%<br/>Tempo e sessione salvati nel Diario.</p><div className="px-progress"><i style={{width:`${progress/required.length*100}%`}}/></div><p>{progress}/{required.length} arredi essenziali · saldo {money(p.balanceCents)}</p><button className="px-primary" onClick={closeReceipt}>Continua la tua storia</button></Popup>}
  {/* Kept mounted while closed: the ORIGINAL metronome engine keeps playing. */}
  <div className={`px-metro-veil ${metro?'px-open':''}`} aria-hidden={!metro}>
   <section className="px-dialog px-metro-dialog" role="dialog" aria-modal={metro} aria-label="Metronomo originale"><header><h2>Metronomo</h2><button onClick={()=>setMetro(false)} aria-label="Chiudi metronomo">×</button></header><MetronomeScreen embedded onState={metState} stopSignal={stopSignal}/></section>
  </div>
 </div>;
}
