import { useCallback,useEffect,useRef,useState,type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { store,useStore } from '../data/store';
import MetronomeScreen from '../screens/MetronomeScreen';
import Scene,{Sprite} from './Scene';
import { ITEMS,MAPS,itemsForMap,ownedOnMap,mapUnlocked,selectMap,begin,pause,resume,finish,tick,buy,bonusFor,completed,clock,type Receipt } from './model';
import { pixel,usePixel } from './state';
import './pixel.css';
import './design.css';
import {Picks,PickWallet,MapThumbnail} from './Currency';
import {Play,Save,ShoppingCart,Music2,Map as MapIcon,Sparkles,LockKeyhole,Clock3} from 'lucide-react';
import {mapInfo} from './maps';
function Popup({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}) {
 const box=useRef<HTMLElement>(null);
 useEffect(()=>{const old=document.activeElement as HTMLElement;box.current?.focus();const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'){const all=box.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);old?.focus();};},[onClose]);
 return createPortal(<div className="px-root px-overlay-root"><div className="px-veil" onClick={onClose}><section className="px-dialog" ref={box} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button onClick={onClose} aria-label="Chiudi finestra">×</button></header>{children}</section></div></div>,document.body);
}
export default function PixelStory({active}:{active:boolean}) {
 const st=useStore();const p=usePixel();const [scene,setScene]=useState(false);const [shop,setShop]=useState(false);const [exit,setExit]=useState(false);const [timer,setTimer]=useState(false);const [metro,setMetro]=useState(false);const [receipt,setReceipt]=useState<Receipt|null>(null);const [selected,setSelected]=useState('');const [stopSignal,setStopSignal]=useState(0);const [met,setMet]=useState({running:false,bpm:100,flash:0});const [delta,setDelta]=useState<{id:number;amount:number}|null>(null);const [notice,setNotice]=useState('');const lastEuro=useRef(Math.floor(p.balanceCents/100));
 const closeShop=useCallback(()=>setShop(false),[]), closeExit=useCallback(()=>setExit(false),[]), closeTimer=useCallback(()=>setTimer(false),[]), closeReceipt=useCallback(()=>setReceipt(null),[]);
 const metroBox=useRef<HTMLElement>(null);
 useEffect(()=>{if(!metro)return;const old=document.activeElement as HTMLElement;metroBox.current?.focus();const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setMetro(false);}if(e.key==='Tab'){const all=metroBox.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===metroBox.current)){e.preventDefault();first.focus();}}};document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);old?.focus();};},[metro]);
 const metState=useCallback((running:boolean,bpm:number,flash:number)=>setMet({running,bpm,flash}),[]);
 const floating=(amount:number)=>setDelta({id:Date.now(),amount});
 const flushReceipts=useCallback(async()=>{for(const r of pixel.get().receipts.filter(r=>!r.recorded)){await store.recordPixelSession(r.id,r.songId,r.startedAt,r.activeMs/1000);pixel.update(s=>({...s,receipts:s.receipts.map(x=>x.id===r.id?{...x,recorded:true}:x)}));}},[]);
 useEffect(()=>{flushReceipts();},[flushReceipts]);
 useEffect(()=>{const t=window.setInterval(()=>{if(active&&pixel.get().session?.status==='running')pixel.update(s=>tick(s,Date.now()));},500);const stop=()=>pixel.update(s=>pause(s,Date.now()));window.addEventListener('pagehide',stop);return()=>{clearInterval(t);window.removeEventListener('pagehide',stop);stop();};},[active]);
 useEffect(()=>{if(!active){pixel.update(s=>pause(s,Date.now()));setScene(false);setMetro(false);setStopSignal(v=>v+1);}},[active]);
 useEffect(()=>{const euro=Math.floor(p.balanceCents/100);if(euro>lastEuro.current&&p.session?.status==='running')floating((euro-lastEuro.current)*100);lastEuro.current=euro;},[p.balanceCents,p.session?.status]);
 useEffect(()=>{if(!delta)return;const t=setTimeout(()=>setDelta(null),1800);return()=>clearTimeout(t);},[delta]);
 useEffect(()=>{if(!scene||!active)return;document.body.classList.add('pixel-session');let lock:{release:()=>void}|undefined;const request=async()=>{try{lock=await (navigator as Navigator & {wakeLock?:{request:(s:string)=>Promise<{release:()=>void}>}}).wakeLock?.request('screen');}catch{}};void request();return()=>{document.body.classList.remove('pixel-session');lock?.release();};},[scene,active]);
 const pauseAndLeave=()=>{pixel.update(s=>pause(s,Date.now()));setScene(false);setExit(false);setMetro(false);setStopSignal(v=>v+1);};
 const end=()=>{if(!pixel.update(s=>finish(s,Date.now())))return;void flushReceipts();setReceipt(pixel.get().receipts[0]??null);setScene(false);setExit(false);setTimer(false);setMetro(false);setStopSignal(v=>v+1);};
 const start=()=>{let song=st.songs.find(s=>selected?s.id===selected:s.title==='Studio libero');if(!song){song=store.addSong('Studio libero');}const s=song;const ok=pixel.update(v=>begin(v,s.id,s.title,Date.now(),`px-${crypto.randomUUID()}`));if(ok)setScene(true);};
 const doResume=()=>{if(pixel.update(s=>resume(s,Date.now())))setScene(true);};
 const map=mapInfo(p.mapId),items=itemsForMap(p.mapId),owned=ownedOnMap(p,p.mapId);const bonus=bonusFor(p.owned);const required=items.filter(i=>i.required);const progress=required.filter(i=>owned.includes(i.id)).length;
 const buyItem=(id:string)=>{const i=ITEMS.find(i=>i.id===id)!;if(pixel.update(s=>buy(s,id))){floating(-i.price*100);setNotice(`${i.name} è nella tua stanza!`);}};
 const interact=(id:string)=>pixel.update(s=>({...s,...(id==='rain'?{rainOn:!s.rainOn}:id==='lamp'?{lampOn:!s.lampOn}:id==='deskLight'?{deskLightOn:!s.deskLightOn}:{fireOn:!s.fireOn})}));
 return <div className={`px-root ${scene?'px-in-session':''}`}>
  {!scene&&<button className="px-cheat" onClick={()=>{if(pixel.update(s=>({...s,balanceCents:s.balanceCents+100000})))floating(100000);}}>+ 1000 plettri</button>}
  {pixel.getError()&&<div className="px-error" role="alert">{pixel.getError()}</div>}
  {!scene&&<div className="px-lobby"><div className="px-eyebrow">IL TUO ANGOLO DI MUSICA</div><h1>Pixel Story</h1><p>Un minuto di studio. Un pezzetto di casa.</p><div className="px-wallet"><div className="px-wallet-main"><PickWallet/><div className="px-wallet-number"><span>I tuoi plettri</span><strong data-testid="pixel-balance"><Picks cents={p.balanceCents}/></strong></div></div><div className="px-wallet-footer"><span><Sparkles aria-hidden="true"/> Bonus permanente +{bonus}%</span><span>1 plettro / minuto</span></div></div><div className="px-map-picker" aria-label="Le tue mappe">{MAPS.map((m,index)=><button key={m.id} className={m.id===p.mapId?'px-map-active':''} disabled={!!p.session||!mapUnlocked(p,m.id)} aria-label={`Mappa ${m.name}${mapUnlocked(p,m.id)?'':' bloccata'}`} aria-pressed={m.id===p.mapId} onClick={()=>pixel.update(v=>selectMap(v,m.id))}><MapThumbnail index={index}/><span className="px-map-copy"><span>{index+1}. {m.name}</span><small>{!mapUnlocked(p,m.id)&&<LockKeyhole aria-hidden="true"/>}{mapUnlocked(p,m.id)?(completed(p,m.id)?'✓ Completata':'Disponibile'):`Completa ${MAPS[index-1]?.name}`}</small></span></button>)}</div><div className="px-preview"><Scene state={p} running={false} bpm={met.bpm} flash={0} onClock={()=>setTimer(true)} onMetro={()=>setMetro(true)} onBack={()=>setNotice('Avvia una sessione per entrare nella stanza.')} onShop={()=>setShop(true)} onObject={interact}/></div><div className="px-map-title"><h2>{map.name}</h2><span>{progress}/{required.length} essenziali</span></div><div className="px-progress"><i style={{width:`${progress/required.length*100}%`}}/></div>{completed(p,p.mapId)&&<div className="px-complete"><MapIcon aria-hidden="true"/><div><strong>Mappa completata!</strong><p>{p.mapId==='stage'?'Tutte le mappe completate! Puoi continuare a studiare dove preferisci.':`${MAPS[MAPS.findIndex(m=>m.id===p.mapId)+1].name} sbloccato.`}</p></div></div>}
   {p.session?<div className="px-session-card"><strong>Sessione in pausa</strong><span className="px-session-subtitle">{p.session.title}</span><div className="px-session-stats"><span><Clock3 aria-hidden="true"/>{clock(p.session.activeMs)}</span><span><Picks cents={p.session.earnedCents}/> plettri guadagnati</span></div><button className="px-primary" onClick={doResume}><Play aria-hidden="true" fill="currentColor"/>Riprendi lo studio</button><button onClick={end}><Save aria-hidden="true"/>Termina e salva</button></div>:<><label className="px-select-label">Cosa studi?<select aria-label="Brano della sessione" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Studio libero</option>{st.songs.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><button className="px-primary px-start" onClick={start}>Entra e inizia a studiare</button></>}
   <div className="px-lobby-actions"><button onClick={()=>{setNotice('');setShop(true);}}><ShoppingCart aria-hidden="true"/>Negozio e arredi</button><button onClick={()=>{store.updateSettings({pixelStory:false});}}><Music2 aria-hidden="true"/>Torna allo Studio classico</button></div><p className="px-small">1 plettro / minuto effettivo · Le pause non producono plettri.<br/>Il bonus viene fissato all’inizio della sessione.</p>
  </div>}
  {scene&&createPortal(<div className="px-root px-stage px-in-session"><button className="px-cheat" onClick={()=>{if(pixel.update(s=>({...s,balanceCents:s.balanceCents+100000})))floating(100000);}}>+ 1000 plettri</button><Scene state={p} running={met.running} bpm={met.bpm} flash={met.flash} onClock={()=>setTimer(true)} onMetro={()=>setMetro(true)} onBack={()=>setExit(true)} onObject={interact}/>{p.session?.status==='paused'&&<button className="px-resume-overlay" onClick={()=>pixel.update(s=>resume(s,Date.now()))}>In pausa · Riprendi</button>}</div>,document.body)}
  {delta&&createPortal(<div key={delta.id} className={`px-money-float ${delta.amount<0?'px-negative':''}`} aria-live="polite">{delta.amount>=0?'+':''}<Picks cents={delta.amount}/></div>,document.body)}
  {shop&&<Popup title={`Negozio · ${map.name}`} onClose={closeShop}><div className="px-shop-top"><strong><Picks cents={p.balanceCents}/></strong><span>Bonus +{bonus}%</span></div>{notice&&<p role="status" className="px-notice">{notice}</p>}<p className="px-small">Completa i {required.length} arredi essenziali. Gli extra sono facoltativi.</p><div className="px-shop-grid">{items.map(i=><article key={i.id} className={owned.includes(i.id)?'px-owned':''}><div className="px-item-art"><Sprite id={i.id}/></div><div className="px-item-copy"><span className="px-item-type">{i.included?'INCLUSO':i.required?'ESSENZIALE':'EXTRA'}{i.bonus>0?` · +${i.bonus}%`:''}</span><h3>{i.name}</h3><p>{i.description}</p><button aria-label={owned.includes(i.id)?`${i.name} acquistato`:`Compra ${i.name}`} disabled={owned.includes(i.id)||p.balanceCents<i.price*100} onClick={()=>buyItem(i.id)}>{owned.includes(i.id)?'✓ Nella stanza':<><Picks cents={i.price*100}/> · Compra</>}</button></div></article>)}</div></Popup>}
  {exit&&<Popup title="Lasci la tua stanza?" onClose={closeExit}><p>Hai studiato {clock(p.session?.activeMs??0)}. Il metronomo continua finché scegli cosa fare.</p><div className="px-dialog-actions"><button className="px-primary" onClick={pauseAndLeave}>Metti in pausa</button><button onClick={end}>Termina sessione</button><button onClick={closeExit}>Annulla</button></div></Popup>}
  {timer&&<Popup title="Orologio di studio" onClose={closeTimer}><div className="px-timer-big" data-testid="pixel-elapsed">{clock(p.session?.activeMs??0)}</div><p>{p.session?.title??'Nessuna sessione avviata'} · {p.session?.status==='running'?'In corso':'In pausa'}</p><p>Guadagnati: <strong><Picks cents={p.session?.earnedCents??0}/></strong><br/>1 plettro/min + {p.session?.bonus??bonus}%</p>{p.session&&<button className="px-primary" onClick={()=>{if(pixel.get().session?.status==='running')setStopSignal(v=>v+1);pixel.update(s=>s.session?.status==='running'?pause(s,Date.now()):resume(s,Date.now()));}}>{p.session.status==='running'?'Metti in pausa il tempo':'Riprendi il tempo'}</button>}</Popup>}
  {receipt&&<Popup title="Una bella sessione ✦" onClose={closeReceipt}><p>{receipt.title}</p><div className="px-timer-big">{clock(receipt.activeMs)}</div><div className="px-reward">+<Picks cents={receipt.earnedCents}/></div><p>Base <Picks cents={Math.floor(receipt.activeMs/600)}/> · bonus +{receipt.bonus}%<br/>Tempo e sessione salvati nel Diario.</p><div className="px-progress"><i style={{width:`${progress/required.length*100}%`}}/></div><p>{progress}/{required.length} arredi essenziali · saldo <Picks cents={p.balanceCents}/></p><button className="px-primary" onClick={closeReceipt}>Continua la tua storia</button></Popup>}
  {/* Kept mounted while closed: the ORIGINAL metronome engine keeps playing. */}
  {createPortal(<div className={`px-metro-veil ${metro?'px-open':''}`} aria-hidden={!metro} onClick={e=>{if(e.target===e.currentTarget)setMetro(false);}}>
   <section ref={metroBox} tabIndex={-1} className="px-dialog px-metro-dialog" role="dialog" aria-modal={metro} aria-label="Metronomo originale"><header><h2>Metronomo</h2><button onClick={()=>setMetro(false)} aria-label="Chiudi metronomo">×</button></header><div className="px-original-metronome"><MetronomeScreen embedded onState={metState} stopSignal={stopSignal}/></div></section>
  </div>,document.body)}
 </div>;
}
