import {useState} from 'react';
import {ChevronLeft,ChevronRight,Plus,X} from 'lucide-react';
import {store,useStore} from '../data/store';
import {Sheet,Card} from '../ui/primitives';
import {uid} from '../lib/utils';
import {dayKey,shiftDay,ALL_DAYS,PATHS,plan,bestFor,type Milestone,type Path} from './planner';
export function Calendar({open,onClose}:{open:boolean;onClose:()=>void}){
 const st=useStore(),[month,setMonth]=useState(dayKey().slice(0,7)+'-01'),[selected,setSelected]=useState(dayKey()),[edit,setEdit]=useState<Milestone|null|undefined>();
 const first=new Date(month+'T12:00:00'),offset=(first.getDay()+6)%7,start=shiftDay(month,-offset),cells=Array.from({length:42},(_,i)=>shiftDay(start,i));
 const move=(n:number)=>{const d=new Date(month+'T12:00:00');d.setMonth(d.getMonth()+n);setMonth(dayKey(d))};
 return <><Sheet open={open} onClose={onClose} title="Calendario"><div className="smart-toolbar"><button className="icon-btn" aria-label="Mese precedente" onClick={()=>move(-1)}><ChevronLeft/></button><h3>{first.toLocaleDateString('it-IT',{month:'long',year:'numeric'})}</h3><button className="icon-btn" aria-label="Mese successivo" onClick={()=>move(1)}><ChevronRight/></button><button className="tiny" onClick={()=>{setMonth(dayKey().slice(0,7)+'-01');setSelected(dayKey())}}>Oggi</button></div><div className="smart-calendar">{['L','M','M','G','V','S','D'].map((d,i)=><small key={i}>{d}</small>)}{cells.map(date=><button key={date} aria-label={`Traguardi ${date}`} aria-pressed={date===selected} className={`${date.slice(0,7)!==month.slice(0,7)?'muted':''} ${date===dayKey()?'today':''}`} onClick={()=>{setSelected(date);setEdit(null)}}><span>{Number(date.slice(-2))}</span>{st.milestones.some(m=>m.date===date)&&<i/>}</button>)}</div><div className="smart-toolbar"><h3>{new Date(selected+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'long'})}</h3><button className="btn btn-soft btn-sm" onClick={()=>setEdit(null)}><Plus size={16}/>Traguardo</button></div>{st.milestones.filter(m=>m.date===selected).map(m=><button className="smart-song" key={m.id} onClick={()=>setEdit(m)}><b>{st.songs.find(s=>s.id===m.songId)?.title??m.title}</b><ChevronRight/></button>)}<button className="btn btn-soft" onClick={onClose}>Chiudi calendario</button></Sheet>{edit!==undefined&&<GoalEditor date={selected} milestone={edit} onClose={()=>setEdit(undefined)}/>}</>;
}
export function GoalEditor({date=dayKey(),milestone,onClose,songId}:{date?:string;milestone:Milestone|null;onClose:()=>void;songId?:string}){
 const st=useStore(),[linked,setLinked]=useState(milestone?.songId??songId??''),[title,setTitle]=useState(milestone?.title??''),[due,setDue]=useState(milestone?.date??date),[start,setStart]=useState(milestone?.startBpm??st.songs.find(s=>s.id===songId)?.lastBpm??60),[final,setFinal]=useState(st.songs.find(s=>s.id===(milestone?.songId??songId))?.goalBpm??100),[path,setPath]=useState<Path>(milestone?.path??'relax');
 const valid=!!due&&(linked?Number.isInteger(start)&&Number.isInteger(final)&&start>=20&&final>=start&&final<=400:!!title.trim());
 const draft:Milestone={id:milestone?.id??'',date:due,title,songId:linked||null,startBpm:start,path,createdAt:milestone?.createdAt??Date.now()},preview=linked&&valid?plan(draft,final,bestFor(linked,st.studyResults),st.settings.studyDays??ALL_DAYS):null;
 return <Sheet open onClose={onClose} title={milestone?'Modifica traguardo':'Nuovo traguardo'}><form className="smart-form" onSubmit={e=>{e.preventDefault();if(!valid)return;if(linked)store.setSongGoal(linked,final);store.saveMilestone({...draft,id:milestone?.id??uid('goal')});onClose()}}><label>Brano o traguardo<select aria-label="Brano o traguardo" value={linked} onChange={e=>{setLinked(e.target.value);const s=st.songs.find(s=>s.id===e.target.value);if(s){setStart(s.lastBpm??60);setFinal(s.goalBpm??100)}}}><option value="">Traguardo personalizzato</option>{st.songs.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>{!linked&&<label>Traguardo<input aria-label="Traguardo" required value={title} onChange={e=>setTitle(e.target.value)}/></label>}<label>Scadenza<input aria-label="Scadenza" type="date" required value={due} onChange={e=>setDue(e.target.value)}/></label>{linked&&<><div className="smart-columns"><label>BPM attuali<input aria-label="BPM attuali" type="number" min={20} max={400} required value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>BPM finali<input aria-label="BPM finali" type="number" min={start} max={400} required value={final} onChange={e=>setFinal(Number(e.target.value))}/></label></div><label>Percorso<select aria-label="Percorso" value={path} onChange={e=>setPath(e.target.value as Path)}>{Object.entries(PATHS).map(([p,c])=><option key={p} value={p}>{c.label} · circa +{c.pace} BPM/giorno</option>)}</select></label>{preview&&<Card className="card-pad"><p>Completamento previsto: {preview.completion?new Date(preview.completion+'T12:00:00').toLocaleDateString('it-IT'):'non disponibile'}</p>{preview.warning&&<p role="status" className="row-sub">{preview.warning}</p>}{preview.alternative&&<button type="button" className="btn btn-soft btn-sm" onClick={()=>setPath(preview.alternative!)}>Usa {PATHS[preview.alternative].label}</button>}{preview.suggestedDate&&!preview.alternative&&<button type="button" className="btn btn-soft btn-sm" onClick={()=>setDue(preview.suggestedDate!)}>Sposta al {new Date(preview.suggestedDate+'T12:00:00').toLocaleDateString('it-IT')}</button>}</Card>}</>}<div className="smart-toolbar"><button className="btn btn-primary" type="submit" disabled={!valid}>Salva traguardo</button><button type="button" className="btn btn-soft" onClick={onClose}>Annulla</button>{milestone&&<button type="button" className="btn btn-danger" onClick={()=>{store.deleteMilestone(milestone.id);onClose()}}>Elimina traguardo</button>}</div></form></Sheet>;
}
