import {useEffect,useState} from 'react';
import {store,useStore} from '../data/store';
import {Card,SectionTitle,Switch} from '../ui/primitives';
import {ALL_DAYS} from './planner';
import {authorizeNotifications,defaults,syncNotifications,needsInstall} from './notifications';
const status=(s:string)=>s==='granted'?'Consentito':s==='denied'?'Non consentito':s==='unsupported'?'Non supportato':'Da autorizzare';
export function StudySettings(){
 const st=useStore(),prefs={...defaults,...st.settings.notifications},days=st.settings.studyDays??ALL_DAYS;
 const [permission,setPermission]=useState('prompt'),[microphone,setMicrophone]=useState('prompt'),[info,setInfo]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;const listeners:PermissionStatus[]=[];const refresh=async()=>{setPermission('Notification'in window?Notification.permission:'unsupported');try{const p=await navigator.permissions.query({name:'microphone' as PermissionName});if(alive){setMicrophone(p.state);p.onchange=()=>setMicrophone(p.state);listeners.push(p)}}catch{}};void refresh();window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{alive=false;for(const p of listeners)p.onchange=null;window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[]);
 const update=(patch:Partial<typeof prefs>)=>{store.updateSettings({notifications:{...prefs,...patch}});void syncNotifications().then(()=>setInfo('Promemoria sincronizzati.')).catch(e=>setInfo(e.message))};
 const ask=async()=>{setBusy(true);try{await authorizeNotifications();setInfo('Notifiche autorizzate e promemoria sincronizzati.')}catch(e){setInfo((e as Error).message)}finally{setPermission('Notification'in window?Notification.permission:'unsupported');setBusy(false)}};
 const askMic=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());setMicrophone('granted');setInfo('Microfono autorizzato per l’accordatore. Il metronomo non richiede il microfono.')}catch{setMicrophone('denied');setInfo('Microfono non disponibile o bloccato. Controlla i permessi del sito nel browser e, su iPhone, Impostazioni → Safari → Microfono. L’accordatore richiede il microfono; il metronomo no.')}};
 return <><SectionTitle>Giorni di studio</SectionTitle><Card className="card-pad"><div className="smart-days">{[1,2,3,4,5,6,0].map((day,i)=><button key={day} className={`btn btn-sm ${days.includes(day)?'btn-primary':'btn-soft'}`} aria-label={['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'][i]} aria-pressed={days.includes(day)} onClick={()=>store.updateSettings({studyDays:days.includes(day)?days.filter(d=>d!==day):[...days,day]})}>{['L','M','M','G','V','S','D'][i]}</button>)}</div><p className="row-sub">Obiettivi e promemoria seguono questi giorni.{!days.length?' Nessun giorno selezionato: i percorsi sono sospesi.':''}</p></Card><SectionTitle>Notifiche e promemoria</SectionTitle><Card className="card-pad smart-form"><div className="smart-toolbar"><b>Notifiche</b><Switch label="Notifiche" on={prefs.enabled} onChange={v=>v?void ask():update({enabled:false})}/></div><label>Orario giornaliero<input type="time" aria-label="Orario del promemoria giornaliero" value={prefs.time} onChange={e=>update({time:e.target.value})}/></label>{(['daily','deadlines','incomplete'] as const).map((kind,i)=><div className="smart-toolbar" key={kind}><span>{['Sessione e riepilogo giornaliero','Scadenze vicine','Obiettivi incompleti'][i]}</span><Switch label={['Sessione e riepilogo giornaliero','Scadenze vicine','Obiettivi incompleti'][i]} on={prefs[kind]} onChange={v=>update({[kind]:v})}/></div>)}<p className="row-sub">Un riepilogo all’orario scelto; un eventuale richiamo dopo 3 ore, solo se resta lavoro. Nessuna notifica nei giorni di riposo. {needsInstall()?'Su iPhone installa la PWA: Safari → Condividi → Aggiungi alla schermata Home.':''}</p></Card><SectionTitle>Permessi</SectionTitle><Card className="card-pad"><p><b>Notifiche</b> · {status(permission)}</p><button className="btn btn-soft" onClick={()=>void ask()}>{busy?'Autorizzazione in corso…':'Richiedi autorizzazione notifiche'}</button><p style={{marginTop:18}}><b>Audio / Microfono</b> · {status(microphone)}</p><button className="btn btn-soft" onClick={()=>void askMic()}>Richiedi autorizzazione microfono</button><p className="row-sub">Il pulsante verifica il microfono per l’accordatore. La riproduzione del metronomo si abilita premendo Avvia.</p>{info&&<p className="row-sub" role="status">{info}</p>}</Card></>;
}
